-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.event
(
    id serial NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    created timestamp without time zone NOT NULL DEFAULT now(),
    updated timestamp without time zone NOT NULL DEFAULT now(),
    name text COLLATE pg_catalog."default",
    venue integer NOT NULL,
    event_type integer NOT NULL,
    date date NOT NULL,
    CONSTRAINT event_pkey PRIMARY KEY (id),
    CONSTRAINT event_name_date_venue_key UNIQUE (name, date, venue),
    CONSTRAINT event_uuid_key UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS public.event_performer
(
    event integer NOT NULL,
    performer integer NOT NULL,
    created timestamp without time zone NOT NULL DEFAULT now(),
    updated timestamp without time zone NOT NULL DEFAULT now(),
    headliner boolean NOT NULL,
    slot integer NOT NULL DEFAULT 0,
    CONSTRAINT event_performer_pkey PRIMARY KEY (event, performer),
    CONSTRAINT "One performer per slot" UNIQUE (event, slot)
);

CREATE TABLE IF NOT EXISTS public.event_promoter
(
    event integer NOT NULL,
    promoter integer NOT NULL,
    created timestamp without time zone NOT NULL DEFAULT now(),
    updated timestamp without time zone NOT NULL DEFAULT now(),
    "primary" boolean NOT NULL,
    CONSTRAINT event_promoter_pkey PRIMARY KEY (event, promoter)
);

CREATE TABLE IF NOT EXISTS public.event_type
(
    id serial NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."default" NOT NULL,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT event_type_pkey PRIMARY KEY (id),
    CONSTRAINT event_type_uuid_key UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS public.festival
(
    id serial NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    promoter integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT festival_pkey1 PRIMARY KEY (id),
    CONSTRAINT festival_uuid_key1 UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS public.festival_alias
(
    id serial NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    festival integer NOT NULL,
    alias text COLLATE pg_catalog."default" NOT NULL,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT festival_alias_pkey1 PRIMARY KEY (id),
    CONSTRAINT festival_alias_alias_key1 UNIQUE (alias),
    CONSTRAINT festival_alias_uuid_key1 UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS public.festival_promoter
(
    festival integer NOT NULL,
    promoter integer NOT NULL,
    role text COLLATE pg_catalog."default",
    CONSTRAINT festival_promoter_pkey PRIMARY KEY (festival, promoter)
);

CREATE TABLE IF NOT EXISTS public.festival_venue
(
    festival integer NOT NULL,
    venue integer NOT NULL,
    stage_order integer,
    is_primary boolean DEFAULT false,
    CONSTRAINT festival_venue_pkey PRIMARY KEY (festival, venue)
);

CREATE TABLE IF NOT EXISTS public.goose_db_version
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT goose_db_version_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.image_location
(
    id serial NOT NULL,
    root text COLLATE pg_catalog."default" NOT NULL,
    created timestamp without time zone NOT NULL DEFAULT now(),
    updated timestamp without time zone NOT NULL DEFAULT now(),
    pattern text COLLATE pg_catalog."default" NOT NULL,
    date_from_exif boolean NOT NULL DEFAULT false,
    include_parent boolean NOT NULL DEFAULT false,
    ignore_dirs text[] COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT image_location_pkey PRIMARY KEY (id),
    CONSTRAINT image_location_root_pattern_key UNIQUE (root, pattern)
);

CREATE TABLE IF NOT EXISTS public.image_location_scans
(
    id serial NOT NULL,
    location integer NOT NULL,
    created timestamp without time zone NOT NULL DEFAULT now(),
    updated timestamp without time zone NOT NULL DEFAULT now(),
    scan_time timestamp without time zone NOT NULL DEFAULT now(),
    successful integer NOT NULL DEFAULT 0,
    inconsistent integer NOT NULL DEFAULT 0,
    failed integer NOT NULL DEFAULT 0,
    CONSTRAINT image_location_scans_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.performer
(
    id serial NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    created timestamp without time zone NOT NULL DEFAULT now(),
    updated timestamp without time zone NOT NULL DEFAULT now(),
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT performer_pkey PRIMARY KEY (id),
    CONSTRAINT performer_uuid_key UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS public.performer_alias
(
    id serial NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    performer integer NOT NULL,
    alias text COLLATE pg_catalog."default" NOT NULL,
    created timestamp without time zone NOT NULL DEFAULT now(),
    updated timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT performer_alias_pkey1 PRIMARY KEY (id),
    CONSTRAINT performer_alias_alias_key1 UNIQUE (alias),
    CONSTRAINT performer_alias_uuid_key UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS public.promoter
(
    id serial NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    created timestamp without time zone NOT NULL DEFAULT now(),
    updated timestamp without time zone NOT NULL DEFAULT now(),
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT promoter_pkey PRIMARY KEY (id),
    CONSTRAINT promoter_uuid_key UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS public.promoter_alias
(
    id serial NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    promoter integer NOT NULL,
    alias text COLLATE pg_catalog."default" NOT NULL,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT promoter_alias_pkey1 PRIMARY KEY (id),
    CONSTRAINT promoter_alias_alias_key1 UNIQUE (alias),
    CONSTRAINT promoter_alias_uuid_key UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS public.source_image
(
    id serial NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    created timestamp without time zone NOT NULL DEFAULT now(),
    updated timestamp without time zone NOT NULL DEFAULT now(),
    event integer NOT NULL,
    source integer NOT NULL,
    directory text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    CONSTRAINT source_image_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.venue
(
    id serial NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    created timestamp without time zone NOT NULL DEFAULT now(),
    updated timestamp without time zone NOT NULL DEFAULT now(),
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT venue_pkey PRIMARY KEY (id),
    CONSTRAINT venue_uuid_key UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS public.venue_alias
(
    id serial NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    venue integer NOT NULL,
    alias text COLLATE pg_catalog."default" NOT NULL,
    created timestamp without time zone NOT NULL DEFAULT now(),
    updated timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT venue_alias_pkey1 PRIMARY KEY (id),
    CONSTRAINT venue_alias_alias_key1 UNIQUE (alias),
    CONSTRAINT venue_alias_uuid_key UNIQUE (uuid)
);

ALTER TABLE IF EXISTS public.event
    ADD CONSTRAINT "Venue for Event" FOREIGN KEY (venue)
    REFERENCES public.venue (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.event
    ADD CONSTRAINT event_event_type_fkey FOREIGN KEY (event_type)
    REFERENCES public.event_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.event_performer
    ADD CONSTRAINT event_performer_event_fkey FOREIGN KEY (event)
    REFERENCES public.event (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.event_performer
    ADD CONSTRAINT event_performer_performer_fkey FOREIGN KEY (performer)
    REFERENCES public.performer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.event_promoter
    ADD CONSTRAINT event_promoter_event_fkey FOREIGN KEY (event)
    REFERENCES public.event (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.event_promoter
    ADD CONSTRAINT event_promoter_promoter_fkey FOREIGN KEY (promoter)
    REFERENCES public.promoter (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.festival
    ADD CONSTRAINT festival_promoter_id_fkey1 FOREIGN KEY (promoter)
    REFERENCES public.promoter (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.festival_alias
    ADD CONSTRAINT festival_alias_festival_id_fkey FOREIGN KEY (festival)
    REFERENCES public.festival (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.festival_promoter
    ADD CONSTRAINT festival_promoter_festival_id_fkey FOREIGN KEY (festival)
    REFERENCES public.festival (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.festival_promoter
    ADD CONSTRAINT festival_promoter_promoter_id_fkey FOREIGN KEY (promoter)
    REFERENCES public.promoter (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.festival_venue
    ADD CONSTRAINT festival_venue_festival_id_fkey FOREIGN KEY (festival)
    REFERENCES public.festival (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.festival_venue
    ADD CONSTRAINT festival_venue_venue_id_fkey FOREIGN KEY (venue)
    REFERENCES public.venue (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.image_location_scans
    ADD CONSTRAINT image_location_scans_location_fkey FOREIGN KEY (location)
    REFERENCES public.image_location (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.performer_alias
    ADD CONSTRAINT performer_alias_performer_fkey1 FOREIGN KEY (performer)
    REFERENCES public.performer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.promoter_alias
    ADD CONSTRAINT promoter_alias_promoter_fkey1 FOREIGN KEY (promoter)
    REFERENCES public.promoter (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.source_image
    ADD CONSTRAINT source_image_event_fkey FOREIGN KEY (event)
    REFERENCES public.event (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.source_image
    ADD CONSTRAINT source_image_source_fkey FOREIGN KEY (source)
    REFERENCES public.image_location (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.venue_alias
    ADD CONSTRAINT venue_alias_venue_fkey1 FOREIGN KEY (venue)
    REFERENCES public.venue (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;