// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dbcollections.sql

package database

import (
	"context"
	"time"
)

const getPatternConsts = `-- name: GetPatternConsts :many
SELECT pattern FROM stage_role
ORDER BY pattern
`

func (q *Queries) GetPatternConsts(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPatternConsts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var pattern string
		if err := rows.Scan(&pattern); err != nil {
			return nil, err
		}
		items = append(items, pattern)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastModifiedPatternConsts = `-- name: LastModifiedPatternConsts :one
SELECT last_modified FROM dbcollections_meta 
WHERE table_name = 'stage_role'
LIMIT 1
`

func (q *Queries) LastModifiedPatternConsts(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, lastModifiedPatternConsts)
	var last_modified time.Time
	err := row.Scan(&last_modified)
	return last_modified, err
}
