// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_types.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createEventType = `-- name: CreateEventType :one
INSERT INTO event_type (name)
VALUES ($1)
RETURNING id, uuid, name
`

type CreateEventTypeRow struct {
	ID   int32
	Uuid uuid.UUID
	Name string
}

func (q *Queries) CreateEventType(ctx context.Context, name string) (CreateEventTypeRow, error) {
	row := q.db.QueryRowContext(ctx, createEventType, name)
	var i CreateEventTypeRow
	err := row.Scan(&i.ID, &i.Uuid, &i.Name)
	return i, err
}

const deleteEventType = `-- name: DeleteEventType :exec
DELETE FROM event_type
WHERE id = $1
`

func (q *Queries) DeleteEventType(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEventType, id)
	return err
}

const getEventType = `-- name: GetEventType :one
SELECT id, uuid, name
FROM event_type
WHERE id = $1
`

type GetEventTypeRow struct {
	ID   int32
	Uuid uuid.UUID
	Name string
}

func (q *Queries) GetEventType(ctx context.Context, id int32) (GetEventTypeRow, error) {
	row := q.db.QueryRowContext(ctx, getEventType, id)
	var i GetEventTypeRow
	err := row.Scan(&i.ID, &i.Uuid, &i.Name)
	return i, err
}

const listEventTypes = `-- name: ListEventTypes :many
SELECT id, uuid, name
FROM event_type
ORDER BY name
`

type ListEventTypesRow struct {
	ID   int32
	Uuid uuid.UUID
	Name string
}

func (q *Queries) ListEventTypes(ctx context.Context) ([]ListEventTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventTypesRow
	for rows.Next() {
		var i ListEventTypesRow
		if err := rows.Scan(&i.ID, &i.Uuid, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventType = `-- name: UpdateEventType :one
UPDATE event_type
SET name = $2
WHERE id = $1
RETURNING id, uuid, name
`

type UpdateEventTypeParams struct {
	ID   int32
	Name string
}

type UpdateEventTypeRow struct {
	ID   int32
	Uuid uuid.UUID
	Name string
}

func (q *Queries) UpdateEventType(ctx context.Context, arg UpdateEventTypeParams) (UpdateEventTypeRow, error) {
	row := q.db.QueryRowContext(ctx, updateEventType, arg.ID, arg.Name)
	var i UpdateEventTypeRow
	err := row.Scan(&i.ID, &i.Uuid, &i.Name)
	return i, err
}
