// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: festival.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createFestival = `-- name: CreateFestival :one
INSERT INTO festival (
    name,
    promoter_id,
    start_date,
    end_date,
    description
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, uuid, name, promoter_id, start_date, end_date, description
`

type CreateFestivalParams struct {
	Name        string
	PromoterID  int32
	StartDate   time.Time
	EndDate     time.Time
	Description sql.NullString
}

func (q *Queries) CreateFestival(ctx context.Context, arg CreateFestivalParams) (Festival, error) {
	row := q.db.QueryRowContext(ctx, createFestival,
		arg.Name,
		arg.PromoterID,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
	)
	var i Festival
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.PromoterID,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
	)
	return i, err
}

const createFestivalAlias = `-- name: CreateFestivalAlias :one
INSERT INTO festival_alias (
    festival_id,
    alias
) VALUES (
    $1, $2
)
RETURNING id, uuid, festival_id, alias, created, updated
`

type CreateFestivalAliasParams struct {
	FestivalID int32
	Alias      string
}

func (q *Queries) CreateFestivalAlias(ctx context.Context, arg CreateFestivalAliasParams) (FestivalAlias, error) {
	row := q.db.QueryRowContext(ctx, createFestivalAlias, arg.FestivalID, arg.Alias)
	var i FestivalAlias
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FestivalID,
		&i.Alias,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteFestival = `-- name: DeleteFestival :exec
DELETE FROM festival
WHERE id = $1
`

func (q *Queries) DeleteFestival(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFestival, id)
	return err
}

const deleteFestivalAlias = `-- name: DeleteFestivalAlias :exec
DELETE FROM festival_alias
WHERE id = $1
`

func (q *Queries) DeleteFestivalAlias(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFestivalAlias, id)
	return err
}

const getFestival = `-- name: GetFestival :one
SELECT id, uuid, name, promoter_id, start_date, end_date, description FROM festival
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFestival(ctx context.Context, id int32) (Festival, error) {
	row := q.db.QueryRowContext(ctx, getFestival, id)
	var i Festival
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.PromoterID,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
	)
	return i, err
}

const getFestivalAlias = `-- name: GetFestivalAlias :one
SELECT id, uuid, festival_id, alias, created, updated FROM festival_alias
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFestivalAlias(ctx context.Context, id int32) (FestivalAlias, error) {
	row := q.db.QueryRowContext(ctx, getFestivalAlias, id)
	var i FestivalAlias
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FestivalID,
		&i.Alias,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listFestivalAliases = `-- name: ListFestivalAliases :many
SELECT id, uuid, festival_id, alias, created, updated FROM festival_alias
ORDER BY alias
`

func (q *Queries) ListFestivalAliases(ctx context.Context) ([]FestivalAlias, error) {
	rows, err := q.db.QueryContext(ctx, listFestivalAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FestivalAlias
	for rows.Next() {
		var i FestivalAlias
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.FestivalID,
			&i.Alias,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFestivals = `-- name: ListFestivals :many
SELECT id, uuid, name, promoter_id, start_date, end_date, description FROM festival
ORDER BY start_date DESC
`

func (q *Queries) ListFestivals(ctx context.Context) ([]Festival, error) {
	rows, err := q.db.QueryContext(ctx, listFestivals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Festival
	for rows.Next() {
		var i Festival
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.PromoterID,
			&i.StartDate,
			&i.EndDate,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFestival = `-- name: UpdateFestival :one
UPDATE festival
SET
    name = $2,
    promoter_id = $3,
    start_date = $4,
    end_date = $5,
    description = $6
WHERE id = $1
RETURNING id, uuid, name, promoter_id, start_date, end_date, description
`

type UpdateFestivalParams struct {
	ID          int32
	Name        string
	PromoterID  int32
	StartDate   time.Time
	EndDate     time.Time
	Description sql.NullString
}

func (q *Queries) UpdateFestival(ctx context.Context, arg UpdateFestivalParams) (Festival, error) {
	row := q.db.QueryRowContext(ctx, updateFestival,
		arg.ID,
		arg.Name,
		arg.PromoterID,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
	)
	var i Festival
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.PromoterID,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
	)
	return i, err
}

const updateFestivalAlias = `-- name: UpdateFestivalAlias :one
UPDATE festival_alias
SET
    festival_id = $2,
    alias = $3
WHERE id = $1
RETURNING id, uuid, festival_id, alias, created, updated
`

type UpdateFestivalAliasParams struct {
	ID         int32
	FestivalID int32
	Alias      string
}

func (q *Queries) UpdateFestivalAlias(ctx context.Context, arg UpdateFestivalAliasParams) (FestivalAlias, error) {
	row := q.db.QueryRowContext(ctx, updateFestivalAlias, arg.ID, arg.FestivalID, arg.Alias)
	var i FestivalAlias
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FestivalID,
		&i.Alias,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
