// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image_location.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const createImageLocation = `-- name: CreateImageLocation :one
INSERT INTO image_location (
    root,
    pattern,
    date_from_exif,
    include_parent,
    ignore_dirs,
    active
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, root, created, updated, pattern, date_from_exif, include_parent, ignore_dirs, active
`

type CreateImageLocationParams struct {
	Root          string
	Pattern       string
	DateFromExif  bool
	IncludeParent bool
	IgnoreDirs    []string
	Active        bool
}

func (q *Queries) CreateImageLocation(ctx context.Context, arg CreateImageLocationParams) (ImageLocation, error) {
	row := q.db.QueryRowContext(ctx, createImageLocation,
		arg.Root,
		arg.Pattern,
		arg.DateFromExif,
		arg.IncludeParent,
		pq.Array(arg.IgnoreDirs),
		arg.Active,
	)
	var i ImageLocation
	err := row.Scan(
		&i.ID,
		&i.Root,
		&i.Created,
		&i.Updated,
		&i.Pattern,
		&i.DateFromExif,
		&i.IncludeParent,
		pq.Array(&i.IgnoreDirs),
		&i.Active,
	)
	return i, err
}

const deleteImageLocation = `-- name: DeleteImageLocation :exec
DELETE FROM image_location
WHERE id = $1
`

func (q *Queries) DeleteImageLocation(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteImageLocation, id)
	return err
}

const getImageLocation = `-- name: GetImageLocation :one
SELECT id, root, created, updated, pattern, date_from_exif, include_parent, ignore_dirs, active FROM image_location
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetImageLocation(ctx context.Context, id int32) (ImageLocation, error) {
	row := q.db.QueryRowContext(ctx, getImageLocation, id)
	var i ImageLocation
	err := row.Scan(
		&i.ID,
		&i.Root,
		&i.Created,
		&i.Updated,
		&i.Pattern,
		&i.DateFromExif,
		&i.IncludeParent,
		pq.Array(&i.IgnoreDirs),
		&i.Active,
	)
	return i, err
}

const listImageLocations = `-- name: ListImageLocations :many
SELECT id, root, created, updated, pattern, date_from_exif, include_parent, ignore_dirs, active FROM image_location
ORDER BY root
`

func (q *Queries) ListImageLocations(ctx context.Context) ([]ImageLocation, error) {
	rows, err := q.db.QueryContext(ctx, listImageLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImageLocation
	for rows.Next() {
		var i ImageLocation
		if err := rows.Scan(
			&i.ID,
			&i.Root,
			&i.Created,
			&i.Updated,
			&i.Pattern,
			&i.DateFromExif,
			&i.IncludeParent,
			pq.Array(&i.IgnoreDirs),
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImageLocation = `-- name: UpdateImageLocation :one
UPDATE image_location
SET
    root = $2,
    pattern = $3,
    date_from_exif = $4,
    include_parent = $5,
    ignore_dirs = $6,
    active = $7,
    updated = now()
WHERE id = $1
RETURNING id, root, created, updated, pattern, date_from_exif, include_parent, ignore_dirs, active
`

type UpdateImageLocationParams struct {
	ID            int32
	Root          string
	Pattern       string
	DateFromExif  bool
	IncludeParent bool
	IgnoreDirs    []string
	Active        bool
}

func (q *Queries) UpdateImageLocation(ctx context.Context, arg UpdateImageLocationParams) (ImageLocation, error) {
	row := q.db.QueryRowContext(ctx, updateImageLocation,
		arg.ID,
		arg.Root,
		arg.Pattern,
		arg.DateFromExif,
		arg.IncludeParent,
		pq.Array(arg.IgnoreDirs),
		arg.Active,
	)
	var i ImageLocation
	err := row.Scan(
		&i.ID,
		&i.Root,
		&i.Created,
		&i.Updated,
		&i.Pattern,
		&i.DateFromExif,
		&i.IncludeParent,
		pq.Array(&i.IgnoreDirs),
		&i.Active,
	)
	return i, err
}
