// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID        int32
	Uuid      uuid.UUID
	Created   time.Time
	Updated   time.Time
	Name      sql.NullString
	Venue     int32
	EventType int32
	Date      time.Time
}

type EventPerformer struct {
	Event     int32
	Performer int32
	Created   time.Time
	Updated   time.Time
	Headliner bool
	Slot      int32
}

type EventPromoter struct {
	Event    int32
	Promoter int32
	Created  time.Time
	Updated  time.Time
	Primary  bool
}

// The types of event possible - examples music gig, music festival, comedy gig
type EventType struct {
	ID      int32
	Created time.Time
	Updated time.Time
	Name    string
}

type Festival struct {
	PromoterID  int32
	StartDate   time.Time
	EndDate     time.Time
	Website     sql.NullString
	Description sql.NullString
}

type FestivalAlias struct {
	ID         int32
	Uuid       uuid.UUID
	FestivalID int32
	Alias      string
	Created    time.Time
	Updated    time.Time
}

type FestivalPromoter struct {
	FestivalID int32
	PromoterID int32
	Role       sql.NullString
}

type FestivalVenue struct {
	FestivalID int32
	VenueID    int32
	StageOrder sql.NullInt32
	IsPrimary  sql.NullBool
}

type ImageLocation struct {
	ID            int32
	Root          string
	Created       time.Time
	Updated       time.Time
	Pattern       string
	DateFromExif  bool
	IncludeParent bool
	IgnoreDirs    []string
	Active        bool
}

type ImageLocationScan struct {
	ID           int32
	Location     int32
	Created      time.Time
	Updated      time.Time
	ScanTime     time.Time
	Successful   int32
	Inconsistent int32
	Failed       int32
}

type Performer struct {
	ID      int32
	Uuid    uuid.UUID
	Created time.Time
	Updated time.Time
	Name    string
}

type PerformerAlias struct {
	ID        int32
	Uuid      uuid.UUID
	Performer int32
	Alias     string
	Created   time.Time
	Updated   time.Time
}

type Promoter struct {
	ID      int32
	Uuid    uuid.UUID
	Created time.Time
	Updated time.Time
	Name    string
}

type PromoterAlias struct {
	ID       int32
	Uuid     uuid.UUID
	Promoter int32
	Alias    string
	Created  time.Time
	Updated  time.Time
}

type SourceImage struct {
	ID      int32
	Uuid    uuid.UUID
	Created time.Time
	Updated time.Time
	Event   int32
	Source  int32
}

type Venue struct {
	ID      int32
	Uuid    uuid.UUID
	Created time.Time
	Updated time.Time
	Name    string
}

type VenueAlias struct {
	ID      int32
	Uuid    uuid.UUID
	Venue   int32
	Alias   string
	Created time.Time
	Updated time.Time
}
