// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: performer_alias.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPerformerAlias = `-- name: CreatePerformerAlias :one
INSERT INTO performer_alias (performer, alias)
VALUES ($1, $2)
RETURNING id, uuid, performer, created, updated, alias
`

type CreatePerformerAliasParams struct {
	Performer int32
	Alias     string
}

type CreatePerformerAliasRow struct {
	ID        int32
	Uuid      uuid.UUID
	Performer int32
	Created   time.Time
	Updated   time.Time
	Alias     string
}

func (q *Queries) CreatePerformerAlias(ctx context.Context, arg CreatePerformerAliasParams) (CreatePerformerAliasRow, error) {
	row := q.db.QueryRowContext(ctx, createPerformerAlias, arg.Performer, arg.Alias)
	var i CreatePerformerAliasRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Performer,
		&i.Created,
		&i.Updated,
		&i.Alias,
	)
	return i, err
}

const deletePerformerAlias = `-- name: DeletePerformerAlias :exec
DELETE FROM performer_alias
WHERE id = $1
`

func (q *Queries) DeletePerformerAlias(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePerformerAlias, id)
	return err
}

const getPerformerAlias = `-- name: GetPerformerAlias :one
SELECT id, uuid, performer, created, updated, alias FROM performer_alias
WHERE id = $1
`

type GetPerformerAliasRow struct {
	ID        int32
	Uuid      uuid.UUID
	Performer int32
	Created   time.Time
	Updated   time.Time
	Alias     string
}

func (q *Queries) GetPerformerAlias(ctx context.Context, id int32) (GetPerformerAliasRow, error) {
	row := q.db.QueryRowContext(ctx, getPerformerAlias, id)
	var i GetPerformerAliasRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Performer,
		&i.Created,
		&i.Updated,
		&i.Alias,
	)
	return i, err
}

const listPerformerAliases = `-- name: ListPerformerAliases :many
SELECT id, uuid, performer, created, updated, alias FROM performer_alias
ORDER BY alias
`

type ListPerformerAliasesRow struct {
	ID        int32
	Uuid      uuid.UUID
	Performer int32
	Created   time.Time
	Updated   time.Time
	Alias     string
}

func (q *Queries) ListPerformerAliases(ctx context.Context) ([]ListPerformerAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPerformerAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPerformerAliasesRow
	for rows.Next() {
		var i ListPerformerAliasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Performer,
			&i.Created,
			&i.Updated,
			&i.Alias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerformerAlias = `-- name: UpdatePerformerAlias :one
UPDATE performer_alias
SET performer = $1, alias = $2, updated = NOW()
WHERE id = $3
RETURNING id, uuid, performer, created, updated, alias
`

type UpdatePerformerAliasParams struct {
	Performer int32
	Alias     string
	ID        int32
}

type UpdatePerformerAliasRow struct {
	ID        int32
	Uuid      uuid.UUID
	Performer int32
	Created   time.Time
	Updated   time.Time
	Alias     string
}

func (q *Queries) UpdatePerformerAlias(ctx context.Context, arg UpdatePerformerAliasParams) (UpdatePerformerAliasRow, error) {
	row := q.db.QueryRowContext(ctx, updatePerformerAlias, arg.Performer, arg.Alias, arg.ID)
	var i UpdatePerformerAliasRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Performer,
		&i.Created,
		&i.Updated,
		&i.Alias,
	)
	return i, err
}
