// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: performer.sql

package database

import (
	"context"
)

const createPerformer = `-- name: CreatePerformer :one
INSERT INTO performer (name)
VALUES ($1)
RETURNING id, uuid, created, updated, name
`

func (q *Queries) CreatePerformer(ctx context.Context, name string) (Performer, error) {
	row := q.db.QueryRowContext(ctx, createPerformer, name)
	var i Performer
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Updated,
		&i.Name,
	)
	return i, err
}

const deletePerformer = `-- name: DeletePerformer :exec
DELETE FROM performer
WHERE id = $1
`

func (q *Queries) DeletePerformer(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePerformer, id)
	return err
}

const getPerformer = `-- name: GetPerformer :one
SELECT id, uuid, created, updated, name FROM performer
WHERE id = $1
`

func (q *Queries) GetPerformer(ctx context.Context, id int32) (Performer, error) {
	row := q.db.QueryRowContext(ctx, getPerformer, id)
	var i Performer
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Updated,
		&i.Name,
	)
	return i, err
}

const getPerformerByName = `-- name: GetPerformerByName :one
SELECT id, uuid, created, updated, name FROM performer
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetPerformerByName(ctx context.Context, name string) (Performer, error) {
	row := q.db.QueryRowContext(ctx, getPerformerByName, name)
	var i Performer
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Updated,
		&i.Name,
	)
	return i, err
}

const listPerformers = `-- name: ListPerformers :many
SELECT id, uuid, created, updated, name FROM performer
ORDER BY name
`

func (q *Queries) ListPerformers(ctx context.Context) ([]Performer, error) {
	rows, err := q.db.QueryContext(ctx, listPerformers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Performer
	for rows.Next() {
		var i Performer
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Created,
			&i.Updated,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerformer = `-- name: UpdatePerformer :one
UPDATE performer
SET name = $1, updated = NOW()
WHERE id = $2
RETURNING id, uuid, created, updated, name
`

type UpdatePerformerParams struct {
	Name string
	ID   int32
}

func (q *Queries) UpdatePerformer(ctx context.Context, arg UpdatePerformerParams) (Performer, error) {
	row := q.db.QueryRowContext(ctx, updatePerformer, arg.Name, arg.ID)
	var i Performer
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Updated,
		&i.Name,
	)
	return i, err
}
