// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: promoter_alias.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPromoterAlias = `-- name: CreatePromoterAlias :one
INSERT INTO promoter_alias (promoter, alias)
VALUES ($1, $2)
RETURNING id, uuid, promoter, created, updated, alias
`

type CreatePromoterAliasParams struct {
	Promoter int32
	Alias    string
}

type CreatePromoterAliasRow struct {
	ID       int32
	Uuid     uuid.UUID
	Promoter int32
	Created  time.Time
	Updated  time.Time
	Alias    string
}

func (q *Queries) CreatePromoterAlias(ctx context.Context, arg CreatePromoterAliasParams) (CreatePromoterAliasRow, error) {
	row := q.db.QueryRowContext(ctx, createPromoterAlias, arg.Promoter, arg.Alias)
	var i CreatePromoterAliasRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Promoter,
		&i.Created,
		&i.Updated,
		&i.Alias,
	)
	return i, err
}

const deletePromoterAlias = `-- name: DeletePromoterAlias :exec
DELETE FROM promoter_alias
WHERE id = $1
`

func (q *Queries) DeletePromoterAlias(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePromoterAlias, id)
	return err
}

const getPromoterAlias = `-- name: GetPromoterAlias :one
SELECT id, uuid, promoter, created, updated, alias FROM promoter_alias
WHERE id = $1
`

type GetPromoterAliasRow struct {
	ID       int32
	Uuid     uuid.UUID
	Promoter int32
	Created  time.Time
	Updated  time.Time
	Alias    string
}

func (q *Queries) GetPromoterAlias(ctx context.Context, id int32) (GetPromoterAliasRow, error) {
	row := q.db.QueryRowContext(ctx, getPromoterAlias, id)
	var i GetPromoterAliasRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Promoter,
		&i.Created,
		&i.Updated,
		&i.Alias,
	)
	return i, err
}

const listPromoterAliases = `-- name: ListPromoterAliases :many
SELECT id, uuid, promoter, created, updated, alias FROM promoter_alias
ORDER BY alias
`

type ListPromoterAliasesRow struct {
	ID       int32
	Uuid     uuid.UUID
	Promoter int32
	Created  time.Time
	Updated  time.Time
	Alias    string
}

func (q *Queries) ListPromoterAliases(ctx context.Context) ([]ListPromoterAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPromoterAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromoterAliasesRow
	for rows.Next() {
		var i ListPromoterAliasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Promoter,
			&i.Created,
			&i.Updated,
			&i.Alias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromoterAlias = `-- name: UpdatePromoterAlias :one
UPDATE promoter_alias
SET promoter = $1, alias = $2, updated = NOW()
WHERE id = $3
RETURNING id, uuid, promoter, created, updated, alias
`

type UpdatePromoterAliasParams struct {
	Promoter int32
	Alias    string
	ID       int32
}

type UpdatePromoterAliasRow struct {
	ID       int32
	Uuid     uuid.UUID
	Promoter int32
	Created  time.Time
	Updated  time.Time
	Alias    string
}

func (q *Queries) UpdatePromoterAlias(ctx context.Context, arg UpdatePromoterAliasParams) (UpdatePromoterAliasRow, error) {
	row := q.db.QueryRowContext(ctx, updatePromoterAlias, arg.Promoter, arg.Alias, arg.ID)
	var i UpdatePromoterAliasRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Promoter,
		&i.Created,
		&i.Updated,
		&i.Alias,
	)
	return i, err
}
