// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: promoter.sql

package database

import (
	"context"
)

const createPromoter = `-- name: CreatePromoter :one
INSERT INTO promoter (name)
VALUES ($1)
RETURNING id, uuid, created, updated, name
`

func (q *Queries) CreatePromoter(ctx context.Context, name string) (Promoter, error) {
	row := q.db.QueryRowContext(ctx, createPromoter, name)
	var i Promoter
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Updated,
		&i.Name,
	)
	return i, err
}

const deletePromoter = `-- name: DeletePromoter :exec
DELETE FROM promoter
WHERE id = $1
`

func (q *Queries) DeletePromoter(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePromoter, id)
	return err
}

const getPromoter = `-- name: GetPromoter :one
SELECT id, uuid, created, updated, name FROM promoter
WHERE id = $1
`

func (q *Queries) GetPromoter(ctx context.Context, id int32) (Promoter, error) {
	row := q.db.QueryRowContext(ctx, getPromoter, id)
	var i Promoter
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Updated,
		&i.Name,
	)
	return i, err
}

const listPromoters = `-- name: ListPromoters :many
SELECT id, uuid, created, updated, name FROM promoter
ORDER BY name
`

func (q *Queries) ListPromoters(ctx context.Context) ([]Promoter, error) {
	rows, err := q.db.QueryContext(ctx, listPromoters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Promoter
	for rows.Next() {
		var i Promoter
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Created,
			&i.Updated,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromoter = `-- name: UpdatePromoter :one
UPDATE promoter
SET name = $1, updated = NOW()
WHERE id = $2
RETURNING id, uuid, created, updated, name
`

type UpdatePromoterParams struct {
	Name string
	ID   int32
}

func (q *Queries) UpdatePromoter(ctx context.Context, arg UpdatePromoterParams) (Promoter, error) {
	row := q.db.QueryRowContext(ctx, updatePromoter, arg.Name, arg.ID)
	var i Promoter
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Updated,
		&i.Name,
	)
	return i, err
}
