// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stage_role.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createStageRole = `-- name: CreateStageRole :one
INSERT INTO stage_role (pattern)
VALUES ($1)
RETURNING id, uuid, created, updated, pattern
`

type CreateStageRoleRow struct {
	ID      int32
	Uuid    uuid.UUID
	Created time.Time
	Updated time.Time
	Pattern string
}

func (q *Queries) CreateStageRole(ctx context.Context, pattern string) (CreateStageRoleRow, error) {
	row := q.db.QueryRowContext(ctx, createStageRole, pattern)
	var i CreateStageRoleRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Updated,
		&i.Pattern,
	)
	return i, err
}

const deleteStageRole = `-- name: DeleteStageRole :exec
DELETE FROM stage_role
WHERE id = $1
`

func (q *Queries) DeleteStageRole(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteStageRole, id)
	return err
}

const getStageRole = `-- name: GetStageRole :one
SELECT id, uuid, created, updated, pattern FROM stage_role
WHERE id = $1
`

type GetStageRoleRow struct {
	ID      int32
	Uuid    uuid.UUID
	Created time.Time
	Updated time.Time
	Pattern string
}

func (q *Queries) GetStageRole(ctx context.Context, id int32) (GetStageRoleRow, error) {
	row := q.db.QueryRowContext(ctx, getStageRole, id)
	var i GetStageRoleRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Updated,
		&i.Pattern,
	)
	return i, err
}

const listStageRoles = `-- name: ListStageRoles :many
SELECT id, uuid, created, updated, pattern FROM stage_role
ORDER BY pattern
`

type ListStageRolesRow struct {
	ID      int32
	Uuid    uuid.UUID
	Created time.Time
	Updated time.Time
	Pattern string
}

func (q *Queries) ListStageRoles(ctx context.Context) ([]ListStageRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listStageRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStageRolesRow
	for rows.Next() {
		var i ListStageRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Created,
			&i.Updated,
			&i.Pattern,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStageRole = `-- name: UpdateStageRole :one
UPDATE stage_role
SET pattern = $1, updated = NOW()
WHERE id = $2
RETURNING id, uuid, created, updated, pattern
`

type UpdateStageRoleParams struct {
	Pattern string
	ID      int32
}

type UpdateStageRoleRow struct {
	ID      int32
	Uuid    uuid.UUID
	Created time.Time
	Updated time.Time
	Pattern string
}

func (q *Queries) UpdateStageRole(ctx context.Context, arg UpdateStageRoleParams) (UpdateStageRoleRow, error) {
	row := q.db.QueryRowContext(ctx, updateStageRole, arg.Pattern, arg.ID)
	var i UpdateStageRoleRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Updated,
		&i.Pattern,
	)
	return i, err
}
