// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venue_alias.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVenueAlias = `-- name: CreateVenueAlias :one
INSERT INTO venue_alias (venue, alias)
VALUES ($1, $2)
RETURNING id, uuid, venue, created, updated, alias
`

type CreateVenueAliasParams struct {
	Venue int32
	Alias string
}

type CreateVenueAliasRow struct {
	ID      int32
	Uuid    uuid.UUID
	Venue   int32
	Created time.Time
	Updated time.Time
	Alias   string
}

func (q *Queries) CreateVenueAlias(ctx context.Context, arg CreateVenueAliasParams) (CreateVenueAliasRow, error) {
	row := q.db.QueryRowContext(ctx, createVenueAlias, arg.Venue, arg.Alias)
	var i CreateVenueAliasRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Venue,
		&i.Created,
		&i.Updated,
		&i.Alias,
	)
	return i, err
}

const deleteVenueAlias = `-- name: DeleteVenueAlias :exec
DELETE FROM venue_alias
WHERE id = $1
`

func (q *Queries) DeleteVenueAlias(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteVenueAlias, id)
	return err
}

const getVenueAlias = `-- name: GetVenueAlias :one
SELECT id, uuid, venue, created, updated, alias FROM venue_alias
WHERE id = $1
`

type GetVenueAliasRow struct {
	ID      int32
	Uuid    uuid.UUID
	Venue   int32
	Created time.Time
	Updated time.Time
	Alias   string
}

func (q *Queries) GetVenueAlias(ctx context.Context, id int32) (GetVenueAliasRow, error) {
	row := q.db.QueryRowContext(ctx, getVenueAlias, id)
	var i GetVenueAliasRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Venue,
		&i.Created,
		&i.Updated,
		&i.Alias,
	)
	return i, err
}

const listVenueAliases = `-- name: ListVenueAliases :many
SELECT id, uuid, venue, created, updated, alias FROM venue_alias
ORDER BY alias
`

type ListVenueAliasesRow struct {
	ID      int32
	Uuid    uuid.UUID
	Venue   int32
	Created time.Time
	Updated time.Time
	Alias   string
}

func (q *Queries) ListVenueAliases(ctx context.Context) ([]ListVenueAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVenueAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVenueAliasesRow
	for rows.Next() {
		var i ListVenueAliasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Venue,
			&i.Created,
			&i.Updated,
			&i.Alias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenueAlias = `-- name: UpdateVenueAlias :one
UPDATE venue_alias
SET venue = $1, alias = $2, updated = NOW()
WHERE id = $3
RETURNING id, uuid, venue, created, updated, alias
`

type UpdateVenueAliasParams struct {
	Venue int32
	Alias string
	ID    int32
}

type UpdateVenueAliasRow struct {
	ID      int32
	Uuid    uuid.UUID
	Venue   int32
	Created time.Time
	Updated time.Time
	Alias   string
}

func (q *Queries) UpdateVenueAlias(ctx context.Context, arg UpdateVenueAliasParams) (UpdateVenueAliasRow, error) {
	row := q.db.QueryRowContext(ctx, updateVenueAlias, arg.Venue, arg.Alias, arg.ID)
	var i UpdateVenueAliasRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Venue,
		&i.Created,
		&i.Updated,
		&i.Alias,
	)
	return i, err
}
