// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venue.sql

package database

import (
	"context"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venue (
    name
) VALUES (
    $1
) RETURNING id, uuid, created, updated, name
`

func (q *Queries) CreateVenue(ctx context.Context, name string) (Venue, error) {
	row := q.db.QueryRowContext(ctx, createVenue, name)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Updated,
		&i.Name,
	)
	return i, err
}

const deleteVenue = `-- name: DeleteVenue :exec
DELETE FROM venue
WHERE id = $1
`

func (q *Queries) DeleteVenue(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteVenue, id)
	return err
}

const getVenue = `-- name: GetVenue :one
SELECT id, uuid, created, updated, name FROM venue
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVenue(ctx context.Context, id int32) (Venue, error) {
	row := q.db.QueryRowContext(ctx, getVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Updated,
		&i.Name,
	)
	return i, err
}

const listVenues = `-- name: ListVenues :many
SELECT id, uuid, created, updated, name FROM venue
ORDER BY name
`

func (q *Queries) ListVenues(ctx context.Context) ([]Venue, error) {
	rows, err := q.db.QueryContext(ctx, listVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Created,
			&i.Updated,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venue
SET
    name = $2,
    updated = now()
WHERE id = $1
RETURNING id, uuid, created, updated, name
`

type UpdateVenueParams struct {
	ID   int32
	Name string
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRowContext(ctx, updateVenue, arg.ID, arg.Name)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Updated,
		&i.Name,
	)
	return i, err
}
