// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venue_alias.sql

package database

import (
	"context"
)

const listVenueAliases = `-- name: ListVenueAliases :many
SELECT id, venue, created, updated, alias FROM venue_alias
ORDER BY alias
`

func (q *Queries) ListVenueAliases(ctx context.Context) ([]VenueAlias, error) {
	rows, err := q.db.QueryContext(ctx, listVenueAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VenueAlias
	for rows.Next() {
		var i VenueAlias
		if err := rows.Scan(
			&i.ID,
			&i.Venue,
			&i.Created,
			&i.Updated,
			&i.Alias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
